# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='identity',
            field=models.CharField(max_length=50),
        ),
    ]
