# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0002_auto_20170914_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='person',
        ),
        migrations.RemoveField(
            model_name='keylist',
            name='associate',
        ),
        migrations.AddField(
            model_name='keylist',
            name='list',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='person',
            name='identity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='imgurl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
