# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysearch', '0004_auto_20170915_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='born',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
